version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    command: "--smallfiles --logpath=/dev/null"

  myrabbit:
    image: "rabbitmq:3-management"
    hostname: "myrabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "recipes"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "micro-rabbit"

networks:
  default:
    external:
      name: local

